<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TcCourse extends \AppBundle\Entity\TcCourse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'coursename', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'author', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'objectives', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'requirements', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'numbclasses', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'numhrsvideo', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'coursedesc', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'isfree', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'cost', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'imgthumb', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'shortdesc', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'imgcourse', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'authorId', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'creationdate', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'isOnline', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'urlCourseOnline'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'coursename', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'author', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'objectives', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'requirements', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'numbclasses', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'numhrsvideo', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'coursedesc', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'isfree', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'cost', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'imgthumb', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'shortdesc', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'imgcourse', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'authorId', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'creationdate', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'isOnline', '' . "\0" . 'AppBundle\\Entity\\TcCourse' . "\0" . 'urlCourseOnline'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TcCourse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUrlCourseOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlCourseOnline', []);

        return parent::getUrlCourseOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlCourseOnline($urlCourseOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlCourseOnline', [$urlCourseOnline]);

        return parent::setUrlCourseOnline($urlCourseOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOnline', []);

        return parent::getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOnline($isOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOnline', [$isOnline]);

        return parent::setIsOnline($isOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationdate', []);

        return parent::getCreationdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationdate($creationdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationdate', [$creationdate]);

        return parent::setCreationdate($creationdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorId', []);

        return parent::getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorId($authorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorId', [$authorId]);

        return parent::setAuthorId($authorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortdesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortdesc', []);

        return parent::getShortdesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortdesc($shortdesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortdesc', [$shortdesc]);

        return parent::setShortdesc($shortdesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgcourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgcourse', []);

        return parent::getImgcourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgcourse($imgcourse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgcourse', [$imgcourse]);

        return parent::setImgcourse($imgcourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgthumb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgthumb', []);

        return parent::getImgthumb();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgthumb($imgthumb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgthumb', [$imgthumb]);

        return parent::setImgthumb($imgthumb);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setCoursename($coursename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoursename', [$coursename]);

        return parent::setCoursename($coursename);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoursename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoursename', []);

        return parent::getCoursename();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories(\Doctrine\Common\Collections\ArrayCollection $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', [$categories]);

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectives', []);

        return parent::getObjectives();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectives(\Doctrine\Common\Collections\ArrayCollection $objectives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectives', [$objectives]);

        return parent::setObjectives($objectives);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequirements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequirements', []);

        return parent::getRequirements();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequirements(\Doctrine\Common\Collections\ArrayCollection $requirements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequirements', [$requirements]);

        return parent::setRequirements($requirements);
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(\AppBundle\Entity\TcAuthor $author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumbclasses($numbclasses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumbclasses', [$numbclasses]);

        return parent::setNumbclasses($numbclasses);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumbclasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumbclasses', []);

        return parent::getNumbclasses();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumhrsvideo($numhrsvideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumhrsvideo', [$numhrsvideo]);

        return parent::setNumhrsvideo($numhrsvideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumhrsvideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumhrsvideo', []);

        return parent::getNumhrsvideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoursedesc($coursedesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoursedesc', [$coursedesc]);

        return parent::setCoursedesc($coursedesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoursedesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoursedesc', []);

        return parent::getCoursedesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsfree($isfree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsfree', [$isfree]);

        return parent::setIsfree($isfree);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsfree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsfree', []);

        return parent::getIsfree();
    }

    /**
     * {@inheritDoc}
     */
    public function setCost($cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCost', [$cost]);

        return parent::setCost($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function getCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCost', []);

        return parent::getCost();
    }

}
