<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TwClass extends \AppBundle\Entity\TwClass implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'controlPanelId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'sectionId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'classId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'iscompleted', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'clase', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'twSection'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'controlPanelId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'sectionId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'classId', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'iscompleted', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'clase', '' . "\0" . 'AppBundle\\Entity\\TwClass' . "\0" . 'twSection'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TwClass $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTwSection($twSection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwSection', [$twSection]);

        return parent::setTwSection($twSection);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwSection', []);

        return parent::getTwSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setClase(\AppBundle\Entity\TrClass $clase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClase', [$clase]);

        return parent::setClase($clase);
    }

    /**
     * {@inheritDoc}
     */
    public function getClase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClase', []);

        return parent::getClase();
    }

    /**
     * {@inheritDoc}
     */
    public function setControlPanelId($controlPanelId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setControlPanelId', [$controlPanelId]);

        return parent::setControlPanelId($controlPanelId);
    }

    /**
     * {@inheritDoc}
     */
    public function getControlPanelId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getControlPanelId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControlPanelId', []);

        return parent::getControlPanelId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectionId($sectionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectionId', [$sectionId]);

        return parent::setSectionId($sectionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectionId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSectionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectionId', []);

        return parent::getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassId($classId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassId', [$classId]);

        return parent::setClassId($classId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClassId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassId', []);

        return parent::getClassId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIscompleted($iscompleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIscompleted', [$iscompleted]);

        return parent::setIscompleted($iscompleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIscompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIscompleted', []);

        return parent::getIscompleted();
    }

}
