<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrClass extends \AppBundle\Entity\TrClass implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'sectionId', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'classId', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'section', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'classdescription', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'activitytype', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'videourl', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'pdfurl', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'examid', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'files'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'sectionId', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'classId', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'section', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'classdescription', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'activitytype', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'videourl', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'pdfurl', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'examid', '' . "\0" . 'AppBundle\\Entity\\TrClass' . "\0" . 'files'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TrClass $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles($files)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', [$files]);

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function setSection(\AppBundle\Entity\TrCourseSection $section)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', [$section]);

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', []);

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectionId($sectionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectionId', [$sectionId]);

        return parent::setSectionId($sectionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectionId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSectionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectionId', []);

        return parent::getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassId($classId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassId', [$classId]);

        return parent::setClassId($classId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClassId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassId', []);

        return parent::getClassId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassdescription($classdescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassdescription', [$classdescription]);

        return parent::setClassdescription($classdescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassdescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassdescription', []);

        return parent::getClassdescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivitytype($activitytype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivitytype', [$activitytype]);

        return parent::setActivitytype($activitytype);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivitytype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivitytype', []);

        return parent::getActivitytype();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideourl($videourl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideourl', [$videourl]);

        return parent::setVideourl($videourl);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideourl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideourl', []);

        return parent::getVideourl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfurl($pdfurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfurl', [$pdfurl]);

        return parent::setPdfurl($pdfurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfurl', []);

        return parent::getPdfurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamid($examid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamid', [$examid]);

        return parent::setExamid($examid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamid', []);

        return parent::getExamid();
    }

}
